### ISSUE TITLE
xLoader release downloads

### ISSUE THREAD

**Issue by nickcounts** [xinabox/xLoader#1]
I think it will make the end users' lives significantly easier if we can have a single download in the "Latest Release"

Right now, downloading the zip file just gets the contents of the xLoader repo (LICENSE and README) and none of the files.

Can we put all the executables and binaries in the repo so this is a one-click download in the releases?

Hope that made sense 👍

**Comment by brendanvanbreda** [comment]
@nickcounts that will be done with the new firmware release
